version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: stock-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./frontend
    container_name: stock-frontend
    depends_on:
      - backend
    networks:
      - app-network

  # NGINX service
  nginx:
    image: nginx:alpine
    container_name: stock-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network

# Network definition
networks:
  app-network:
    driver: bridge 